#!/bin/bash

function install {
    export NODE_TLS_REJECT_UNAUTHORIZED=0
    corepack enable
    yarn config set nodeLinker node-modules
    yarn set version 4.12.0
    yarn install
}

function start {
    npm run start 
}

$1 "${@:2}"